_allow_dotted_keys:
    value: false
_convert_dict:
    value: true
_fields:
    value:
        batch_size: 256
        device: cpu
        eval_size: 1024
        model: |
            activation: &id001 !!python/tuple
            - false
            - true
            bias: false
            dropout: null
            emb_dim: 64
            ff_dim: 256
            flash: true
            layer_norm: true
            mask: true
            mlp: *id001
            mlp_bias: true
            num_heads: !!python/tuple
            - 1
            - 1
            num_layers: 2
            pos_enc: rotary
            pos_max_len: 32
        ngram: 4
        seed: null
        seq_len: 128
        task: |
            alpha: 1.0
            cardinality: 2
            dist_name: finite_dirichlet
            fixed: false
            name: frm
            ood: false
            order: 2
            random_alpha: 0.2
            random_order: 1
            rho: 0.2
            total_trans: 32
        test_size: 4096
        training: |
            T_max: 20
            eval_iter: 1000
            freeze_out: false
            freeze_value: false
            get_attn: 1000
            get_checkpoints: 1000
            get_probes: 100
            identity_query: false
            learning_rate: 3.0e-05
            num_epochs: 20000
            scheduler: false
            weight_decay: 0.01
        vocab_size: 5
        wandb: |
            project: ICL
        work_dir: frm_results
_locked:
    value: false
_sort_keys:
    value: true
_type_safe:
    value: true
_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
                - 61
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": darwin-arm64
